"""add path back to goals

Revision ID: 1be57bdbd8c9
Revises: 80a6641129f1
Create Date: 2025-12-07 12:06:54.407142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import LtreeType

# revision identifiers, used by Alembic.
revision = '1be57bdbd8c9'
down_revision = '80a6641129f1'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add column as nullable first
    op.add_column('goals', sa.Column('path', LtreeType(), nullable=True,
                                     comment='Materialized path: 1.3.2 — enables O(1) subtree queries'))
    # 2. Fill all existing rows with 'root'
    op.execute("UPDATE goals SET path = 'root'")
    # 3. Now make it NOT NULL
    op.alter_column('goals', 'path', nullable=False)
    # 4. Create index
    op.create_index('ix_goals_path', 'goals', ['path'], unique=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goals_path'), table_name='goals')
    op.drop_column('goals', 'path')
    # ### end Alembic commands ###
