"""Upgrade Task.status to native PostgreSQL ENUM

Revision ID: 7070c89c4679
Revises: f7aa7b36c480
Create Date: 2025-12-08 06:17:03.023474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7070c89c4679'
down_revision = 'f7aa7b36c480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('BACKLOG', 'TODO', 'DOING', 'BLOCKED', 'DONE', name='taskstatus'),
               comment='Current column: backlog → todo → doing → blocked → done',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('BACKLOG', 'TODO', 'DOING', 'BLOCKED', 'DONE', name='taskstatus'),
               comment=None,
               existing_comment='Current column: backlog → todo → doing → blocked → done',
               existing_nullable=False)
    # ### end Alembic commands ###
