"""Create goals table — REAL THIS TIME

Revision ID: db283ae68399
Revises: 
Create Date: 2025-12-06 18:36:11.779402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import LtreeType

# revision identifiers, used by Alembic.
revision = 'db283ae68399'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Owner of the goal — Single Warrior Mode'),
    sa.Column('title', sa.Text(), nullable=False, comment="The name of the goal — e.g., 'Run a marathon'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Why this goal matters — the fire behind it'),
    sa.Column('category', sa.Enum('MARITAL', 'SOCIAL', 'FINANCIAL', 'WORK', 'FAMILY', 'SPIRITUAL', 'HEALTH', 'HOBBY', name='goalcategory'), nullable=False, comment='One of the 8 life domains'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='When this goal should be complete'),
    sa.Column('is_habit', sa.Boolean(), nullable=False, comment='True = auto-create daily instances (Phase 4)'),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', LtreeType(), nullable=False, comment='Materialized path: 1.3.2 — enables O(1) subtree queries'),
    sa.Column('status', sa.Enum('BACKLOG', 'TODO', 'DOING', 'BLOCKED', 'DONE', 'CANCELLED', name='goalstatus'), nullable=False, comment='Current column: backlog → todo → doing → blocked → done'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_path'), 'goals', ['path'], unique=False)
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_path'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
