"""update sqlalchemy enum

Revision ID: f7aa7b36c480
Revises: 1be57bdbd8c9
Create Date: 2025-12-07 14:40:17.485059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7aa7b36c480'
down_revision = '1be57bdbd8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'category',
               existing_type=postgresql.ENUM('marital', 'social', 'financial', 'work', 'family', 'spiritual', 'health', 'hobby', name='goalcategory'),
               nullable=False,
               comment='One of the 8 life domains')
    op.alter_column('goals', 'status',
               existing_type=postgresql.ENUM('backlog', 'todo', 'doing', 'blocked', 'done', 'cancelled', name='goalstatus'),
               comment='Current column: backlog → todo → doing → blocked → done',
               existing_nullable=False,
               existing_server_default=sa.text("'todo'::goalstatus"))
    op.drop_index(op.f('ix_goals_status'), table_name='goals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_goals_status'), 'goals', ['status'], unique=False)
    op.alter_column('goals', 'status',
               existing_type=postgresql.ENUM('backlog', 'todo', 'doing', 'blocked', 'done', 'cancelled', name='goalstatus'),
               comment=None,
               existing_comment='Current column: backlog → todo → doing → blocked → done',
               existing_nullable=False,
               existing_server_default=sa.text("'todo'::goalstatus"))
    op.alter_column('goals', 'category',
               existing_type=postgresql.ENUM('marital', 'social', 'financial', 'work', 'family', 'spiritual', 'health', 'hobby', name='goalcategory'),
               nullable=True,
               comment=None,
               existing_comment='One of the 8 life domains')
    # ### end Alembic commands ###
